image: node:18

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - node_modules/
    - .pnpm-store/

.install_pnpm:
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm config set store-dir .pnpm-store

stages:
  - build
  - lint
  - docker-build

build:
  stage: build
  extends: .install_pnpm
  tags:
    - hva
  script:
    - pnpm install
    - pnpm run build
  artifacts:
    expire_in: 3 days
    paths:
      - dist

quality:
  stage: lint
  needs: [build]
  extends: .install_pnpm
  tags:
    - hva
  script:
    - pnpm run lint

docker-build:
  image: docker:25.0.3
  stage: docker-build
  tags:
    - hva
  only:
    refs:
      - main
  script:
    - docker login gitlab.fdmci.hva.nl:5050 -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t gitlab.fdmci.hva.nl:5050/project-se-dt/2324/team5/pse-fitculture-fe .
    - docker push gitlab.fdmci.hva.nl:5050/project-se-dt/2324/team5/pse-fitculture-fe
