image: maven:3.6.3-jdk-11

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SONAR_SCANNER_OPTS: "-Xmx1024m"

cache:
  paths:
    - .m2/repository
    - target/
    - node_modules/

stages:
  - build
  - quality
  - docker-build
  - deploy

build-job:
  stage: build
  tags:
    - hva
  script:
    - mvn $MAVEN_CLI_OPTS clean package -Dmaven.test.skip=true

unit-test-job:
  stage: quality
  tags:
    - hva
  script:
    - mvn $MAVEN_CLI_OPTS test -Dspring.profiles.active=test

sonar-backend-job:
  image: maven:3.8.3-openjdk-17
  stage: quality
  tags:
    - hva
  script:
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dspring.profiles.active=test -Dsonar.login=$SONAR_TOKEN

sonar-frontend-job:
  image: node:14
  stage: quality
  tags:
    - hva
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - npm install
    - npm install -g sonarqube-scanner
  script:
    - npm run test:unit -- --coverage
    - sonar-scanner -Dsonar.projectKey=your_project_key -Dsonar.organization=your_organization -Dsonar.sources=src -Dsonar.tests=tests -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info -Dsonar.login=$SONAR_TOKEN

docker-build:
  image: docker:25.0.3
  stage: docker-build
  tags:
    - hva
  script:
    - docker login gitlab.fdmci.hva.nl:5050 -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t gitlab.fdmci.hva.nl:5050/project-se-dt/2324/team5/pse-fitculture-be .
    - docker push gitlab.fdmci.hva.nl:5050/project-se-dt/2324/team5/pse-fitculture-be
  only:
    - master

deploy-job:
  stage: deploy
  image: ruby:2.7
  tags:
    - hva
  script:
    - apt-get update -qq && apt-get install -y curl git
    - curl https://cli-assets.heroku.com/install.sh | sh
    - export HEROKU_API_KEY="$HEROKU_PRODUCTION_KEY"
    - git config --global user.email "you@example.com"
    - git config --global user.name "GitLab CI/CD"
    - git remote remove heroku || true
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
    - git remote -v
    - git fetch --unshallow || echo "Repository already fully cloned, skipping unshallow"
    - git push heroku HEAD:refs/heads/main --force
  only:
    - master
