stages:
  - build
  - lint

build:
  image: node:18
  stage: build
  tags:
    - hva
  script:
    - pnpm install
    - pnpm run build
  artifacts:
    expire_in: 3 days
    paths:
      - dist

quality:
  image: node:18
  stage: lint
  tags:
    - hva
  script:
    - pnpm install
    - pnpm run lint
