image: node:18

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - node_modules/
    - .pnpm-store/

before_script:
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - pnpm config set store-dir .pnpm-store

stages:
  - build
  - lint

build:
  stage: build
  tags:
    - hva
  script:
    - pnpm install
    - pnpm run build
  artifacts:
    expire_in: 3 days
    paths:
      - dist

quality:
  stage: lint
  needs: [build]
  tags:
    - hva
  script:
    - pnpm install
    - pnpm run lint
